### ISSUE TITLE
Some Problems

### ISSUE THREAD

**Issue by Sakurapola** [CarryChang/Customer_Satisfaction_Analysis#3]
大佬你好！实践过后生成了各角度情感极性图，想要试下画热力图！大佬能不能分享下直接爬虫下来的带民宿地址的csv文件呀？非常感谢！

**Comment by CarryChang** [comment]
热力图需要搭配Pyechart的heat map和采集后的POI位置坐标数据，直接采集的民宿基本信息是只有位置的文本信息，位置点的坐标信息通过开放的百度POI或者高德POI接口去做位置转换得到的，你可以去试一下哈

**Comment by CarryChang** [comment]
地理位置信息已上传

**Comment by CarryChang** [comment]
pyltp已更改为jieba，增加新模型
